defineModule(sim, list(name = "Biomass_core", description = "A fast and large landscape biomass succession model modified from LANDIS-II Biomass Succession extension, v3.2.1", 
    keywords = c("forest succession", "LANDIS II", "Biomass"), 
    authors = c(person("Yong", "Luo", email = "yluo1@lakeheadu.ca", 
        role = "aut"), person(c("Eliot", "J", "B"), "McIntire", 
        email = "eliot.mcintire@canada.ca", role = c("aut", "cre")), 
        person("Jean", "Marchal", email = "jean.d.marchal@gmail.com", 
            role = "ctb"), person(c("Alex", "M."), "Chubaty", 
            email = "achubaty@for-cast.ca", role = "ctb"), person("Ceres", 
            "Barros", email = "cbarros@mail.ubc.ca", role = "ctb")), 
    childModules = character(0), version = list(Biomass_core = numeric_version("1.3.9")), 
    spatialExtent = raster::extent(rep(NA_real_, 4)), timeframe = as.POSIXlt(c(NA, 
        NA)), timeunit = "year", citation = list("citation.bib"), 
    documentation = list("README.txt", "Biomass_core.Rmd"), reqdPkgs = list("assertthat", 
        "compiler", "crayon", "data.table", "dplyr", "fpCompare", 
        "ggplot2", "grid", "parallel", "purrr", "quickPlot", 
        "raster", "Rcpp", "R.utils", "scales", "sp", "tidyr", 
        "PredictiveEcology/LandR@development (>= 1.0.0.9001)", 
        "PredictiveEcology/pemisc@development", "PredictiveEcology/reproducible@development", 
        "PredictiveEcology/SpaDES.core@development (>= 1.0.8.9000)", 
        "PredictiveEcology/SpaDES.tools@development", "ianmseddy/LandR.CS@master (>= 0.0.2.0002)"), 
    parameters = rbind(defineParameter("calcSummaryBGM", "character", 
        "end", NA, NA, desc = paste("A character vector describing when to calculate the summary of biomass, growth and mortality", 
            "Currently any combination of 5 options is possible:", 
            "'start'- as before vegetation succession events, i.e. before dispersal,", 
            "'postDisp' - after dispersal, 'postRegen' - after post-disturbance regeneration (currently the same as 'start'),", 
            "'postGM' - after growth and mortality, 'postAging' - after aging,", 
            "'end' - at the end of vegetation succesion events, before plotting and saving.", 
            "The 'end' option is always active, being also the default option.", 
            "If NULL, then will skip all summaryBGM related events")), 
        defineParameter("calibrate", "logical", FALSE, desc = "Do calibration? Defaults to FALSE"), 
        defineParameter("cohortDefinitionCols", "character", 
            c("pixelGroup", "speciesCode", "age"), NA, NA, desc = paste("cohortData columns that determine what constitutes a cohort", 
                "This parameter should only be modified if additional modules are adding columns to cohortData")), 
        defineParameter("cutpoint", "numeric", 1e+10, NA, NA, 
            desc = "A numeric scalar indicating how large each chunk of an internal data.table is, when processing by chunks"), 
        defineParameter("gmcsGrowthLimits", "numeric", c(1/1.5 * 
            100, 1.5/1 * 100), NA, NA, paste("if using LandR.CS for climate-sensitive growth and mortality, a percentile", 
            " is used to estimate the effect of climate on growth/mortality ", 
            "(currentClimate/referenceClimate). Upper and lower limits are ", 
            "suggested to circumvent problems caused by very small denominators as well as ", 
            "predictions outside the data range used to generate the model")), 
        defineParameter("gmcsMortLimits", "numeric", c(1/1.5 * 
            100, 1.5/1 * 100), NA, NA, paste("if using LandR.CS for climate-sensitive growth and mortality, a percentile", 
            " is used to estimate the effect of climate on growth/mortality ", 
            "(currentClimate/referenceClimate). Upper and lower limits are ", 
            "suggested to circumvent problems caused by very small denominators as well as ", 
            "predictions outside the data range used to generate the model")), 
        defineParameter("gmcsMinAge", "numeric", 21, 0, NA, paste("if using LandR.CS for climate-sensitive growth and mortality, the minimum", 
            "age for which to predict climate-sensitive growth and mortality.", 
            "Young stands (< 30) are poorly represented by the PSP data used to parameterize the model.")), 
        defineParameter("growthAndMortalityDrivers", "character", 
            "LandR", NA, NA, desc = paste("package name where the following functions can be found:", 
                "calculateClimateEffect, assignClimateEffect", 
                "(see LandR.CS for climate sensitivity, leave default if none desired)")), 
        defineParameter("growthInitialTime", "numeric", start(sim), 
            NA_real_, NA_real_, desc = "Initial time for the growth event to occur"), 
        defineParameter("initialBiomassSource", "character", 
            "cohortData", NA, NA, paste("Currently, there are three options: 'spinUp', 'cohortData', 'biomassMap'. ", 
                "If 'spinUp', it will derive biomass by running spinup derived from Landis-II.", 
                "If 'cohortData', it will be taken from the 'cohortData' object, i.e., it is already correct, by cohort.", 
                "If 'biomassMap', it will be taken from `sim$biomassMap`,", 
                "divided across species using `sim$speciesLayers` percent cover values", 
                "`spinUp` uses `sim$standAgeMap` as the driver, so biomass", 
                "is an output. That means it will be unlikely to match any input information", 
                "about biomass, unless this is set to TRUE, and a `sim$rawBiomassMap` is supplied.")), 
        defineParameter("keepClimateCols", "logical", FALSE, 
            NA, NA, "include growth and mortality predictions in `cohortData`?"), 
        defineParameter("minCohortBiomass", "numeric", 0, NA, 
            NA, desc = "cohorts with biomass below this threshold are removed. Not a LANDIS-II BSM param."), 
        defineParameter("mixedType", "numeric", 2, desc = paste("How to define mixed stands: 1 for any species admixture;", 
            "2 for deciduous > conifer. See `?vegTypeMapGenerator`.")), 
        defineParameter("plotOverstory", "logical", FALSE, NA, 
            NA, desc = "swap max age plot with overstory biomass"), 
        defineParameter("seedingAlgorithm", "character", "wardDispersal", 
            NA_character_, NA_character_, desc = paste("choose which seeding algorithm will be used among", 
                "noSeeding (no horizontal, nor vertical seeding), noDispersal (no horizontal disperal),", 
                "universalDispersal, and wardDispersal (default).", 
                "Species dispersal distances (in the 'species' table) are based", 
                "on LANDIS-II parameters.")), defineParameter("spinupMortalityfraction", 
            "numeric", 0.001, desc = "defines the mortality loss fraction in spin up-stage simulation"), 
        defineParameter("sppEquivCol", "character", "Boreal", 
            NA, NA, "The column in sim$specieEquivalency data.table to use as a naming convention"), 
        defineParameter("successionTimestep", "numeric", 10, 
            NA, NA, paste("defines the simulation time step, default is 10 years.", 
                "Note that growth and mortality always happen on a yearly basis.", 
                "Cohorts younger than this age will not be included in competitive interactions")), 
        defineParameter("vegLeadingProportion", "numeric", 0.8, 
            0, 1, desc = "a number that define whether a species is leading for a given pixel"), 
        defineParameter(".maxMemory", "numeric", 5, NA, NA, desc = "maximum amount of memory (in GB) to use for dispersal calculations."), 
        defineParameter(".plotInitialTime", "numeric", start(sim), 
            NA, NA, desc = paste("Vector of length = 1, describing the simulation time at which the first plot event should occur.", 
                "To plotting off completely use .plots.")), defineParameter(".plotInterval", 
            "numeric", NA, NA, NA, desc = paste("defines the plotting time step.", 
                "If NA, the default, .plotInterval is set to successionTimestep.")), 
        defineParameter(".plots", "character", default = "object", 
            desc = paste("Passed to `types` in Plots (see ?Plots). There are a few plots that are made within this module, if set.", 
                "Note that plots (or their data) saving will ONLY occur at end(sim).", 
                "If  NA plotting is off completely (this includes saving).")), 
        defineParameter(".plotMaps", "logical", TRUE, NA, NA, 
            desc = "Controls whether maps should be plotted or not. Set to FALSE if .plots == NA"), 
        defineParameter(".saveInitialTime", "numeric", NA, NA, 
            NA, desc = paste("Vector of length = 1, describing the simulation time at which the first save event should occur.", 
                "Set to NA if no saving is desired. If not NA, then saving will occur at", 
                ".saveInitialTime with a frequency equal to .saveInterval")), 
        defineParameter(".saveInterval", "numeric", NA, NA, NA, 
            desc = paste("defines the saving time step.", "If NA, the default, .saveInterval is set to successionTimestep.")), 
        defineParameter(".studyAreaName", "character", NA, NA, 
            NA, "Human-readable name for the study area used. If NA, a hash of studyArea will be used."), 
        defineParameter(".useCache", "character", c(".inputObjects", 
            "init"), NA, NA, desc = "Internal. Can be names of events or the whole module name; these will be cached by SpaDES"), 
        defineParameter(".useParallel", "ANY", 2, NA, NA, desc = paste("Used only in seed dispersal.", 
            "If numeric, it will be passed to data.table::setDTthreads and should be <= 2;", 
            "If TRUE, it will be passed to `parallel:makeCluster`;", 
            "and if a cluster object, it will be passed to `parallel::parClusterApplyB`."))), 
    inputObjects = bindrows(expectsInput("biomassMap", "RasterLayer", 
        desc = paste("total biomass raster layer in study area (in g/m2),", 
            "filtered for pixels covered by cohortData.", "Only used if `P(sim)$initialBiomassSource == 'biomassMap'`"), 
        sourceURL = ""), expectsInput("cceArgs", "list", desc = paste("a list of quoted objects used by the `growthAndMortalityDriver` `calculateClimateEffect` function")), 
        expectsInput("cohortData", "data.table", desc = "Columns: B, pixelGroup, speciesCode, Indicating several features about ages and current vegetation of stand"), 
        expectsInput("ecoregion", "data.table", desc = "ecoregion look up table", 
            sourceURL = paste0("https://raw.githubusercontent.com/LANDIS-II-Foundation/", 
                "Extensions-Succession/master/biomass-succession-archive/", 
                "trunk/tests/v6.0-2.0/ecoregions.txt")), expectsInput("ecoregionMap", 
            "RasterLayer", desc = paste("ecoregion map that has mapcodes match ecoregion table and speciesEcoregion table.", 
                "Defaults to a dummy map matching rasterToMatch with two regions")), 
        expectsInput("lastReg", "numeric", desc = "an internal counter keeping track of when the last regeneration event occurred"), 
        expectsInput("minRelativeB", "data.frame", desc = "table defining the cut points to classify stand shadeness"), 
        expectsInput("pixelGroupMap", "RasterLayer", desc = "DESCRIPTION_NEEDED"), 
        expectsInput("rasterToMatch", "RasterLayer", desc = "a raster of the studyArea in the same resolution and projection as biomassMap"), 
        expectsInput("species", "data.table", desc = paste("a table that has species traits such as longevity, shade tolerance, etc.", 
            "Default is partially based on Dominic Cir and Yan's project"), 
            sourceURL = "https://raw.githubusercontent.com/dcyr/LANDIS-II_IA_generalUseFiles/master/speciesTraits.csv"), 
        expectsInput("speciesEcoregion", "data.table", desc = paste("table defining the maxANPP, maxB and SEP, which can change with both ecoregion and simulation time.", 
            "Defaults to a dummy table based on dummy data os biomass, age, ecoregion and land cover class")), 
        expectsInput("speciesLayers", "RasterStack", desc = paste("cover percentage raster layers by species in Canada species map.", 
            "Defaults to the Canadian Forestry Service, National Forest Inventory,", 
            "kNN-derived species cover maps from 2001 using a cover threshold of 10 -", 
            "see https://open.canada.ca/data/en/dataset/ec9e2659-1c29-4ddb-87a2-6aced147a990 for metadata"), 
            sourceURL = paste0("http://ftp.maps.canada.ca/pub/nrcan_rncan/Forests_Foret/", 
                "canada-forests-attributes_attributs-forests-canada/2001-attributes_attributs-2001/")), 
        expectsInput("sppColorVect", "character", desc = paste("A named vector of colors to use for plotting.", 
            "The names must be in sim$speciesEquivalency[[sim$sppEquivCol]],", 
            "and should also contain a color for 'Mixed'")), 
        expectsInput("sppEquiv", "data.table", desc = "table of species equivalencies. See LandR::sppEquivalencies_CA."), 
        expectsInput("studyArea", "SpatialPolygonsDataFrame", 
            desc = paste("Polygon to use as the study area.", 
                "Defaults to  an area in Southwestern Alberta, Canada.")), 
        expectsInput("studyAreaReporting", "SpatialPolygonsDataFrame", 
            desc = paste("multipolygon (typically smaller/unbuffered than studyArea) to use for plotting/reporting.", 
                "Defaults to an area in Southwestern Alberta, Canada.")), 
        expectsInput("sufficientLight", "data.frame", desc = paste("table defining how the species with different shade tolerance respond to stand shadeness.", 
            "Default is based on LANDIS-II Biomass Succession v6.2 parameters"), 
            sourceURL = paste0("https://raw.githubusercontent.com/LANDIS-II-Foundation/", 
                "Extensions-Succession/master/biomass-succession-archive/", 
                "trunk/tests/v6.0-2.0/biomass-succession_test.txt")), 
        expectsInput("treedFirePixelTableSinceLastDisp", "data.table", 
            desc = paste("3 columns: pixelIndex, pixelGroup, and burnTime.", 
                "Each row represents a forested pixel that was burned up to and including this year,", 
                "since last dispersal event, with its corresponding pixelGroup and time it occurred"))), 
    outputObjects = bindrows(createsOutput("activePixelIndex", 
        "integer", desc = "internal use. Keeps track of which pixels are active"), 
        createsOutput("activePixelIndexReporting", "integer", 
            desc = "internal use. Keeps track of which pixels are active in the reporting study area"), 
        createsOutput("ANPPMap", "RasterLayer", desc = "ANPP map at each succession time step"), 
        createsOutput("cohortData", "data.table", desc = "age cohort-biomass table hooked to pixel group map by pixelGroupIndex at succession time step"), 
        createsOutput("ecoregionMap", "RasterLayer", desc = paste("ecoregion map that has mapcodes match ecoregion table and speciesEcoregion table.", 
            "Defaults to a dummy map matching rasterToMatch with two regions")), 
        createsOutput("inactivePixelIndex", "logical", desc = "internal use. Keeps track of which pixels are inactive"), 
        createsOutput("inactivePixelIndexReporting", "integer", 
            desc = "internal use. Keeps track of which pixels are inactive in the reporting study area"), 
        createsOutput("lastFireYear", "numeric", desc = "Year of the most recent fire year"), 
        createsOutput("lastReg", "numeric", desc = "an internal counter keeping track of when the last regeneration event occurred"), 
        createsOutput("minRelativeB", "data.frame", desc = "define the cut points to classify stand shadeness"), 
        createsOutput("mortalityMap", "RasterLayer", desc = "Mortality map at each succession time step"), 
        createsOutput("pixelGroupMap", "RasterLayer", desc = "updated community map at each succession time step"), 
        createsOutput("regenerationOutput", "data.table", desc = "TODO: description needed"), 
        createsOutput("reproductionMap", "RasterLayer", desc = "Regeneration map at each succession time step"), 
        createsOutput("simulatedBiomassMap", "RasterLayer", desc = "Biomass map at each succession time step"), 
        createsOutput("simulationOutput", "data.table", desc = "contains simulation results by ecoregion (main output)"), 
        createsOutput("simulationTreeOutput", "data.table", desc = "Summary of several characteristics about the stands, derived from cohortData"), 
        createsOutput("species", "data.table", desc = paste("a table that has species traits such as longevity, shade tolerance, etc.", 
            "Currently obtained from LANDIS-II Biomass Succession v.6.0-2.0 inputs")), 
        createsOutput("speciesEcoregion", "data.table", desc = "define the maxANPP, maxB and SEP change with both ecoregion and simulation time"), 
        createsOutput("speciesLayers", "RasterStack", desc = "biomass percentage raster layers by species in Canada species map"), 
        createsOutput("spinupOutput", "data.table", desc = "Spin-up output"), 
        createsOutput("summaryBySpecies", "data.table", desc = "The total species biomass, average age and aNPP across the landscape (used for plotting and reporting)."), 
        createsOutput("summaryBySpecies1", "data.table", desc = "No. pixels of each leading vegetation type (used for plotting and reporting)."), 
        createsOutput("summaryLandscape", "data.table", desc = "The averages of total biomass, age and aNPP across the landscape (used for plotting and reporting)."), 
        createsOutput("treedFirePixelTableSinceLastDisp", "data.table", 
            desc = paste("3 columns: pixelIndex, pixelGroup, and burnTime.", 
                "Each row represents a forested pixel that was burned up to and including this year,", 
                "since last dispersal event, with its corresponding pixelGroup and time it occurred")), 
        createsOutput("vegTypeMap", "RasterLayer", desc = "Map of leading species in each pixel, colored according to sim$sppColorVect"))))
